import mongoose from 'mongoose';

const Schema = mongoose.Schema;

let bookings = new Schema(
  {
    id: Number,
    masterId: Number,
    propertyId: Number,
    roomId: Number,
    unitId: Number,
    roomQty: Number,
    offerId: Number,
    status: String,
    subStatus: String,
    arrival: String,
    departure: String,
    numAdult: Number,
    numChild: Number,
    title: String,
    firstName: String,
    lastName: String,
    email: String,
    phone: String,
    mobile: String,
    fax: String,
    company: String,
    address: String,
    city: String,
    state: String,
    postcode: String,
    country: String,
    country2: String,
    arrivalTime: String,
    voucher: String,
    comments: String,
    notes: String,
    message: String,
    groupNote: String,
    custom1: String,
    custom2: String,
    custom3: String,
    custom4: String,
    custom5: String,
    custom6: String,
    custom7: String,
    custom8: String,
    custom9: String,
    custom10: String,
    flagColor: String,
    flagText: String,
    statusCode: Number,
    lang: String,
    referer: String,
    refererEditable: String,
    reference: String,
    apiSourceId: String,
    apiSource: String,
    apiReference: String,
    allowChannelUpdate: String,
    allowAutoAction: String,
    allowReview: String,
    allowCancellation: Object,
    invoiceeId: Number,
    bookingTime: String,
    modifiedTime: String,
    cancelTime: String,
    price: Number,
    deposit: Number,
    tax: Number,
    commission: Number,
    rateDescription: String,
    stripeToken: String,
    apiMessage: String
  },
  { collection: 'Bookings' }
);

export default mongoose.model('bookings', bookings);


