export {default as exercisesModel, Exercise} from './exercises.model'
export {default as exercisesRepoModel, ExercisesRepo} from './exercisesRepo.model'
export {default as instructorsModel, Instructor} from './instructors.model'
export {default as routinesModel, Routines} from './routines.model'
export {default as studentsModel, Student} from './students.model'
export {default as workoutsModel, Workout} from './workouts.model'
