name: Homolog Deploy

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  BUCKET_NAME: ${{secrets.BUCKET_NAME}}
  AWS_COGNITO_POOL_ID: ${{secrets.AWS_COGNITO_POOL_ID}}
  AWS_COGNITO_CLIENT_ID: ${{secrets.AWS_COGNITO_CLIENT_ID}}
  AWS_COGNITO_PERSONAL_POOL_ID: ${{secrets.AWS_COGNITO_PERSONAL_POOL_ID}}
  AWS_COGNITO_PERSONAL_CLIENT_ID: ${{secrets.AWS_COGNITO_PERSONAL_CLIENT_ID}}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: homolog
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install
        run: yarn
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy --stage ${{secrets.NODE_ENV}}
